from fpdf import FPDF
from datetime import datetime

# 1. Define the PDF Layout (The "Design")
class MedicalCV(FPDF):
    def header(self):
        # Logo or App Name
        self.set_font('Arial', 'B', 15)
        self.cell(80) # Move to right
        self.cell(30, 10, 'MedConnect Professional Profile', 0, 0, 'C')
        self.ln(20) # Line break

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        # Page number and timestamp
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        self.cell(0, 10, f'Generated by MedConnect App on {timestamp} - Page ' + str(self.page_no()), 0, 0, 'C')

    def chapter_title(self, label):
        # Section Headers (e.g., "Certifications")
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(200, 220, 255) # Light blue background
        self.cell(0, 6, label, 0, 1, 'L', 1)
        self.ln(4)

    def chapter_body(self, text):
        # Standard text
        self.set_font('Arial', '', 11)
        self.multi_cell(0, 5, text)
        self.ln()

# 2. The Data (In a real app, this comes from your Database)
user_data = {
    "name": "Dr. Sarah Johnson",
    "role": "Chief Resident - Cardiology",
    "hospital": "General Teaching Hospital",
    "license": "MD-5592-X",
    "email": "sarah.j@example.com"
}

# List of courses retrieved from the 'Certificates' table
courses_completed = [
    {"title": "Infection Prevention Control", "provider": "WHO", "date": "2023-10-12", "credits": 1.5},
    {"title": "Management of Hypertension", "provider": "Stanford Medicine", "date": "2023-11-05", "credits": 3.0},
    {"title": "Advanced Cardiac Life Support (ACLS)", "provider": "Red Cross", "date": "2023-12-01", "credits": 4.0},
    {"title": "Digital Health & Telemedicine", "provider": "CDC", "date": "2024-01-15", "credits": 1.0},
]

# 3. Generate the PDF
def generate_pdf_cv(user, courses):
    pdf = MedicalCV()
    pdf.add_page()
    
    # --- HEADER SECTION: User Details ---
    pdf.set_font('Arial', 'B', 16)
    pdf.cell(0, 10, user['name'], 0, 1)
    
    pdf.set_font('Arial', '', 11)
    pdf.cell(0, 6, f"{user['role']} | {user['hospital']}", 0, 1)
    pdf.cell(0, 6, f"License ID: {user['license']}", 0, 1)
    pdf.cell(0, 6, f"Contact: {user['email']}", 0, 1)
    pdf.ln(10) # Add space
    
    # --- SECTION: Professional Summary ---
    pdf.chapter_title("Professional Summary")
    pdf.chapter_body("Dedicated medical practitioner committed to staying current with global healthcare trends. "
                     "Successfully completed continuous professional development (CPD) modules focusing on "
                     "cardiology and public health safety.")
    
    # --- SECTION: Verified Certifications ---
    pdf.chapter_title("Verified Certifications & Courses")
    
    # Table Header
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(90, 8, 'Course Title', 1)
    pdf.cell(50, 8, 'Provider', 1)
    pdf.cell(30, 8, 'Date', 1)
    pdf.cell(20, 8, 'Credits', 1)
    pdf.ln()
    
    # Table Rows
    pdf.set_font('Arial', '', 10)
    total_credits = 0
    
    for course in courses:
        pdf.cell(90, 8, course['title'], 1)
        pdf.cell(50, 8, course['provider'], 1)
        pdf.cell(30, 8, course['date'], 1)
        pdf.cell(20, 8, str(course['credits']), 1)
        pdf.ln()
        total_credits += course['credits']
        
    pdf.ln(5)
    
    # --- SECTION: Totals ---
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(0, 10, f"Total CME Credits Earned: {total_credits}", 0, 1, 'R')
    
    # Save the file
    filename = f"{user['name'].replace(' ', '_')}_CV.pdf"
    pdf.output(filename)
    print(f"✅ Success! PDF generated: {filename}")

# --- EXECUTE ---
if __name__ == "__main__":
    generate_pdf_cv(user_data, courses_completed)